# Header
menu:
  主页: /
  随笔: /categories/随笔
  电影&阅读: /categories/电影阅读
  世界那么大: /categories/世界那么大
  攻城狮那些事儿: /categories/攻城狮那些事儿
  所有文章: /archives

# SubNav
subnav:
  github: https://github.com/LucienLau/
  weibo: http://weibo.com/
  #rss: "#"
  #zhihu: https://zhihu.com
  #douban: "#"
  mail: https://mail.google.com
  #facebook: "#"
  google: https://www.google.com/ncr
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: /assets/images/avatar/avatar.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: smfy
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  七牛云: http://www.qiniu.com/
  多说评论: http://duoshuo.com/
  网易云音乐: http://music.163.com
  Hexo.Themes: https://github.com/hexojs/hexo/wiki/Themes
  在线MarkDwon: https://stackedit.io/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
